#!/usr/bin/env python3
"""Resolve the locked dependency set twice and fail if the freezes differ.

Uses ``uv export --frozen`` into two temp files. Exit 0 when identical.

Usage:
  python scripts/check_dependency_determinism.py
"""
from __future__ import annotations

import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def export_to(path: Path) -> None:
    subprocess.check_call(
        [
            "uv",
            "export",
            "--frozen",
            "--extra",
            "api",
            "--extra",
            "ml",
            "--extra",
            "dev",
            "--no-emit-project",
            "-o",
            str(path),
        ],
        cwd=ROOT,
    )


def normalize(text: str) -> list[str]:
    """Drop path-bearing autogen comments so two exports compare equal."""
    lines: list[str] = []
    for ln in text.splitlines():
        if ln.startswith("#    uv export"):
            continue
        if ln.startswith("# This file was autogenerated"):
            continue
        lines.append(ln)
    return lines


def main() -> int:
    with tempfile.TemporaryDirectory(prefix="hg-deps-") as tmp:
        a = Path(tmp) / "a.txt"
        b = Path(tmp) / "b.txt"
        export_to(a)
        export_to(b)
        left = normalize(a.read_text())
        right = normalize(b.read_text())
        if left != right:
            print("Determinism check FAILED — two frozen exports differ.")
            for i, (x, y) in enumerate(zip(left, right)):
                if x != y:
                    print(f"  line {i}: {x!r} vs {y!r}")
                    break
            if len(left) != len(right):
                print(f"  length {len(left)} vs {len(right)}")
            return 1
        print(f"OK — two successive frozen exports are identical ({len(left)} lines).")
        out = ROOT / "artifacts"
        out.mkdir(exist_ok=True)
        (out / "resolved-deps.txt").write_text("\n".join(left) + "\n")
        return 0


if __name__ == "__main__":
    raise SystemExit(main())
