#!/usr/bin/env python3
"""Regenerate requirements.txt from uv.lock (hash-pinned).

Usage:
  python scripts/export_requirements.py
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "requirements.txt"

HEADER = """\
# GENERATED FILE — do not hand-edit.
# Source of truth: uv.lock (Python 3.12).
# Regenerate with:  python scripts/export_requirements.py
#
"""


def main() -> int:
    raw = subprocess.check_output(
        [
            "uv",
            "export",
            "--frozen",
            "--extra",
            "api",
            "--extra",
            "ml",
            "--no-emit-project",
        ],
        cwd=ROOT,
        text=True,
    )
    kept: list[str] = []
    for ln in raw.splitlines():
        if ln.startswith("# This file was autogenerated"):
            continue
        if ln.startswith("#    uv export"):
            continue
        kept.append(ln)
    while kept and not kept[0].strip():
        kept.pop(0)
    OUT.write_text(HEADER + "\n".join(kept).rstrip() + "\n")
    print(f"wrote {OUT} ({len(kept)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
