#!/usr/bin/env python3
"""Regenerate hash-pinned requirement exports from uv.lock.

Writes:
  * requirements.txt      -- api + ml (production / Docker --require-hashes)
  * requirements-dev.txt  -- api + ml + dev (CI tooling, including import-linter)

Usage:
  python scripts/export_requirements.py
"""
from __future__ import annotations

import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_PROD = ROOT / "requirements.txt"
OUT_DEV = ROOT / "requirements-dev.txt"

HEADER = """\
# GENERATED FILE — do not hand-edit.
# Source of truth: uv.lock (Python 3.12).
# Regenerate with:  python scripts/export_requirements.py
#
"""


def _export(*extras: str) -> list[str]:
    cmd = ["uv", "export", "--frozen", "--no-emit-project"]
    for extra in extras:
        cmd.extend(["--extra", extra])
    raw = subprocess.check_output(cmd, cwd=ROOT, text=True)
    kept: list[str] = []
    for ln in raw.splitlines():
        if ln.startswith("# This file was autogenerated"):
            continue
        if ln.startswith("#    uv export"):
            continue
        kept.append(ln)
    while kept and not kept[0].strip():
        kept.pop(0)
    return kept


def _write(path: Path, lines: list[str]) -> None:
    path.write_text(HEADER + "\n".join(lines).rstrip() + "\n")
    print(f"wrote {path} ({len(lines)} lines)")


def main() -> int:
    _write(OUT_PROD, _export("api", "ml"))
    _write(OUT_DEV, _export("api", "ml", "dev"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
