#!/usr/bin/env python3
"""Write synthetic staging secret payloads (never production credentials).

Usage:
  python scripts/generate_boundary_secret_payloads.py
  python scripts/generate_boundary_secret_payloads.py --print-gcloud
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "tests" / "fixtures" / "boundary" / "staging-secrets.json"
FORMAT = ROOT / "tests" / "fixtures" / "boundary" / "README.md"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--print-gcloud",
        action="store_true",
        help="Print gcloud secret-version add commands for staging (synthetic).",
    )
    args = parser.parse_args(argv)

    sys.path.insert(0, str(ROOT / "src"))
    from heatguard.boundary.api_keys import synthetic_bundle
    from heatguard.boundary.session_tokens import synthetic_session_fixture

    api_keys = synthetic_bundle()
    session = synthetic_session_fixture()
    payload = {
        "warning": "synthetic staging only — never a production credential",
        "environment": "staging",
        "secrets": {
            "HEATGUARD_API_KEY_PEPPER": api_keys["pepper"],
            "HEATGUARD_API_KEY_DIGESTS": api_keys["bundle"],
            "HEATGUARD_SESSION_SIGNING_SECRET": session["signing_secret"],
        },
        "secret_ids": {
            "HEATGUARD_API_KEY_PEPPER": "heatguard-staging-hmac-pepper",
            "HEATGUARD_API_KEY_DIGESTS": "heatguard-staging-integrator-digests",
            "HEATGUARD_SESSION_SIGNING_SECRET": "heatguard-staging-session-signing",
        },
    }

    if args.print_gcloud:
        pepper_id = payload["secret_ids"]["HEATGUARD_API_KEY_PEPPER"]
        digest_id = payload["secret_ids"]["HEATGUARD_API_KEY_DIGESTS"]
        signing_id = payload["secret_ids"]["HEATGUARD_SESSION_SIGNING_SECRET"]
        digest_json = json.dumps(payload["secrets"]["HEATGUARD_API_KEY_DIGESTS"], separators=(",", ":"))
        print(f"printf '%s' {payload['secrets']['HEATGUARD_API_KEY_PEPPER']!r} | gcloud secrets versions add {pepper_id} --data-file=-")
        print(f"printf '%s' {digest_json!r} | gcloud secrets versions add {digest_id} --data-file=-")
        print(f"printf '%s' {payload['secrets']['HEATGUARD_SESSION_SIGNING_SECRET']!r} | gcloud secrets versions add {signing_id} --data-file=-")
        return 0

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    if not FORMAT.exists():
        FORMAT.write_text(
            "Synthetic Secret Manager payloads for staging wiring drills.\n"
            "Never production credentials. Regenerated by\n"
            "`python scripts/generate_boundary_secret_payloads.py`.\n",
            encoding="utf-8",
        )
    print(f"Wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
